// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaintInventory.Server.Data;

#nullable disable

namespace PaintInventory.Server.Migrations
{
    [DbContext(typeof(PaintInventoryDbContext))]
    [Migration("20260921062634_PaintInventory")]
    partial class PaintInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaintInventory.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaintInventory_AuditLogs", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.CoatLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AirTempC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("CoatType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeductFromStock")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DewPointC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("HumidityPct")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("MeasuredThicknessUm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaintIdText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaintReportItemId")
                        .HasColumnType("int");

                    b.Property<string>("PartABatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartAProductId")
                        .HasColumnType("int");

                    b.Property<string>("PartBBatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartBProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RequiredThicknessUm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Shade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StockLocationVendorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubstrateTempC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("PartAProductId");

                    b.HasIndex("PartBProductId");

                    b.HasIndex("StockLocationVendorId");

                    b.HasIndex("PaintReportItemId", "Sequence");

                    b.ToTable("PaintInventory_CoatLines", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultShade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HazardFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MixRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PackVolume")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PartnerProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TracksExpiry")
                        .HasColumnType("bit");

                    b.Property<string>("UnNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Gtin")
                        .IsUnique();

                    b.HasIndex("PartnerProductId");

                    b.ToTable("PaintInventory_Products", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreparedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreparedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ipo");

                    b.ToTable("PaintInventory_Reports", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintReportItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbrasiveBlasting")
                        .HasColumnType("bit");

                    b.Property<bool?>("AdhesionTestPerformed")
                        .HasColumnType("bit");

                    b.Property<int>("AdhesionTestType")
                        .HasColumnType("int");

                    b.Property<int?>("BlastVendorId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("MeasuredTotalDftUm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("MekTestNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaintReportId")
                        .HasColumnType("int");

                    b.Property<string>("PaintingSpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaintingVendorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RequiredTotalDftUm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlastVendorId");

                    b.HasIndex("PaintingVendorId");

                    b.HasIndex("PaintReportId", "ItemNo");

                    b.ToTable("PaintInventory_ReportItems", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.StockBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("OnHandQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaintProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReorderLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.HasIndex("PaintProductId", "VendorId")
                        .IsUnique();

                    b.ToTable("PaintInventory_StockBalances", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BestBefore")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CoatLineId")
                        .HasColumnType("int");

                    b.Property<int?>("CounterpartyVendorId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PackVolume")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaintProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoatLineId");

                    b.HasIndex("CounterpartyVendorId");

                    b.HasIndex("PaintProductId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VendorId");

                    b.ToTable("PaintInventory_StockTransactions", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.SurfacePrep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AirTempC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DewPointC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("GradeOfCleanliness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HumidityPct")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("MeasuredRoughness")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaintReportItemId")
                        .HasColumnType("int");

                    b.Property<string>("RequiredRoughness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SubstrateTempC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaintReportItemId")
                        .IsUnique();

                    b.ToTable("PaintInventory_SurfacePreps", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DoesBlasting")
                        .HasColumnType("bit");

                    b.Property<bool>("DoesPainting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwnCompany")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("StoresStock")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PaintInventory_Vendors", (string)null);
                });

            modelBuilder.Entity("PaintInventory.Server.Models.CoatLine", b =>
                {
                    b.HasOne("PaintInventory.Server.Models.PaintReportItem", "ReportItem")
                        .WithMany("Coats")
                        .HasForeignKey("PaintReportItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintInventory.Server.Models.PaintProduct", "PartAProduct")
                        .WithMany()
                        .HasForeignKey("PartAProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaintInventory.Server.Models.PaintProduct", "PartBProduct")
                        .WithMany()
                        .HasForeignKey("PartBProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaintInventory.Server.Models.Vendor", "StockLocationVendor")
                        .WithMany()
                        .HasForeignKey("StockLocationVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PartAProduct");

                    b.Navigation("PartBProduct");

                    b.Navigation("ReportItem");

                    b.Navigation("StockLocationVendor");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintProduct", b =>
                {
                    b.HasOne("PaintInventory.Server.Models.PaintProduct", "PartnerProduct")
                        .WithMany()
                        .HasForeignKey("PartnerProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PartnerProduct");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintReportItem", b =>
                {
                    b.HasOne("PaintInventory.Server.Models.Vendor", "BlastVendor")
                        .WithMany()
                        .HasForeignKey("BlastVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaintInventory.Server.Models.PaintReport", "Report")
                        .WithMany("Items")
                        .HasForeignKey("PaintReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintInventory.Server.Models.Vendor", "PaintingVendor")
                        .WithMany()
                        .HasForeignKey("PaintingVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlastVendor");

                    b.Navigation("PaintingVendor");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.StockBalance", b =>
                {
                    b.HasOne("PaintInventory.Server.Models.PaintProduct", "PaintProduct")
                        .WithMany("StockBalances")
                        .HasForeignKey("PaintProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaintInventory.Server.Models.Vendor", "Vendor")
                        .WithMany("StockBalances")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaintProduct");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.StockTransaction", b =>
                {
                    b.HasOne("PaintInventory.Server.Models.CoatLine", "CoatLine")
                        .WithMany("StockTransactions")
                        .HasForeignKey("CoatLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PaintInventory.Server.Models.Vendor", "CounterpartyVendor")
                        .WithMany()
                        .HasForeignKey("CounterpartyVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaintInventory.Server.Models.PaintProduct", "PaintProduct")
                        .WithMany("StockTransactions")
                        .HasForeignKey("PaintProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaintInventory.Server.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoatLine");

                    b.Navigation("CounterpartyVendor");

                    b.Navigation("PaintProduct");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.SurfacePrep", b =>
                {
                    b.HasOne("PaintInventory.Server.Models.PaintReportItem", "ReportItem")
                        .WithOne("SurfacePrep")
                        .HasForeignKey("PaintInventory.Server.Models.SurfacePrep", "PaintReportItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportItem");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.CoatLine", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintProduct", b =>
                {
                    b.Navigation("StockBalances");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintReport", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.PaintReportItem", b =>
                {
                    b.Navigation("Coats");

                    b.Navigation("SurfacePrep");
                });

            modelBuilder.Entity("PaintInventory.Server.Models.Vendor", b =>
                {
                    b.Navigation("StockBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
